### ISSUE TITLE
Options used to perform noise reduction?

### ISSUE THREAD

**Issue by rbrito** [inducer/lecture-tube#1]
Dear @inducer,

First of all, I would like to thank you for using only Free (as in Freedom) software. That is highly refreshing (with me being an official Debian Maintainer and caring a lot about Freedom).

I just went to your course homepage and downloaded the videos here to my homepage, but then learned about this wonderful project (yes, I am _very_ much into videos and recording, as you can see from my projects) and I briefly skimmed through your repo, but couldn't find how you are performing noise reduction with audacity.

I could only see that, in one of your scripts, you call audacity with a wave file. Are you removing noise manually (i.e., by trial and error) or do you have something scripted?

Also, I see that you are using a lot of gstreamer pipelines. Did you have any problems when using regular `ffmpeg`? I know that older Debian distributions used to ship `avconv`, but the project decided to move along to regular `ffmpeg` and it has a lot of features and fixes that may make using complicated gstreamer pipelines unnecessary.

Anyway, my main question is regarding noise reduction and if/how you automated the task (which should be quite laborious if done manually).

Thanks,

Rogério.

**Comment by inducer** [comment]
To remove noise on my lecture videos, I simply used the " noise removal" option on the "effects" menu in audacity. It works by having you select a period of silence, from which it seems to build some sort of noise profile, which you can then easily remove from the entire lecture audio. By the nature of it, this is sort of an interactive process, which is hard to script. That said, of all the things I tried, this yielded by far the best results.

In terms of gstreamer vs. ffmpeg, I liked the amount of control that gstreamer gave me, although I have to say that it sometimes fails in very non-obvious ways. At any rate, the scripts exist as they are, and they usually work for me. If you would like to contribute an equivalent ffmpeg version, I would be delighted to have that.
